---
- name: Ensure local folder is present
  ansible.builtin.file:
    path: "{{ splunk_home }}/etc/apps/search/local"
    state: directory
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
    mode: '0755'
  become: true
  when: splunk_listening_port != 'undefined'

- name: Configure Splunk Listening port
  community.general.ini_file:
    path: "{{ splunk_home }}/etc/apps/search/local/inputs.conf"
    section: 'splunktcp://{{ splunk_listening_port }}'
    option: connection_host
    value: 'ip'
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
    mode: '0644'
  become: true
  notify: Restart splunk
  when: splunk_listening_port != 'undefined'
