---
- name: Configure file access control list (facl) settings for splunk user
  when: not least_privileged
  block:
    - name: Install acl package
      ansible.builtin.package:
        name: "acl"
        state: present
      become: true

    - name: Set default facl to allow splunk user to read /var/log
      ansible.posix.acl:
        path: /var/log
        entity: "{{ splunk_nix_user }}"
        etype: user
        permissions: rx
        default: "{{ item }}"
        recursive: true
        state: present
      become: true
      loop:
        - true
        - false

    - name: 'Check if {{ logrotate_file }} is present'
      ansible.builtin.stat:
        path: "{{ logrotate_file }}"
      register: result_logrotate_conf
      become: true

    - name: Add setfacl to logrotate script
      ansible.builtin.lineinfile:
        path: "{{ logrotate_file }}"
        insertbefore: 'endscript'
        line: '        /usr/bin/setfacl -Rm u:{{ splunk_nix_user }}:rx /var/log'
      become: true
      when: result_logrotate_conf.stat.exists

    - name: Check if auditd.conf is present
      ansible.builtin.stat:
        path: /etc/audit/auditd.conf
      register: result_auditd_conf
      become: true

    - name: Allow splunk to read /var/log/audit.log
      community.general.ini_file:
        path: /etc/audit/auditd.conf
        section: null
        option: log_group
        value: "{{ splunk_nix_group }}"
        mode: '0640'
      become: true
      notify:
        - Restart redhat auditd service
        - Restart non-redhat auditd service
      when: result_auditd_conf.stat.exists
