---
- name: "Ensure {{ firewall_service }} package is installed"
  ansible.builtin.package:
    name: "{{ firewall_service }}"
    state: present
  become: true

- name: Configure firewalld for Splunk
  when: firewall_service == "firewalld"
  block:
    - name: Ensure firewalld is Started and Enabled
      ansible.builtin.systemd:
        name: "{{ firewall_service }}"
        state: started
        enabled: true
      become: true

    - name: Add splunk firewalld service
      ansible.builtin.template:
        src: firewalld_service.xml.j2
        dest: /etc/firewalld/services/{{ splunk_firewall_service }}.xml
        backup: true
        mode: '0644'
        owner: root
        group: root
      become: true
      register: firewalld

    - name: Reload firewalld # noqa no-handler
      ansible.builtin.command: firewall-cmd --reload
      become: true
      changed_when: false
      when: firewalld.changed

    - name: Activate splunk firewalld service
      ansible.posix.firewalld:
        service: "{{ splunk_firewall_service }}"
        permanent: true
        state: enabled
        immediate: true
      notify: Reload firewalld
      become: true

- name: Configure UFW for Splunk
  when: firewall_service == "ufw"
  block:
    - name: Ensure SSH is enabled
      community.general.ufw:
        port: 22
        proto: tcp
        rule: allow
        state: enabled
      become: true

    - name: Add splunk port to UFW
      community.general.ufw:
        port: "{{ item.number }}"
        proto: "{{ item.protocol }}"
        rule: allow
        state: reloaded
        comment: "{{ item.desc | default('') }}"
      become: true
      loop: "{{ splunk_firewall_ports }}"
