---
- name: Include Splunk Stop Task
  ansible.builtin.include_tasks: splunk_stop.yml

- name: Disable boot-start
  ansible.builtin.command: "{{ splunk_home }}/bin/splunk disable boot-start"
  become: true
  changed_when: false

- name: Remove splunk folder
  ansible.builtin.file:
    path: "{{ splunk_home }}"
    state: absent
  become: true

- name: Block for non-root splunk user removal
  when: splunk_nix_user != 'root'
  block:
    - name: Remove nix splunk user
      ansible.builtin.user:
        name: "{{ splunk_nix_user }}"
        groups: "{{ splunk_nix_group }}"
        state: absent
        local: "{{ local_os_user }}"
      become: true

    - name: Remove nix splunk group
      ansible.builtin.group:
        name: "{{ splunk_nix_group }}"
        state: absent
        local: "{{ local_os_group }}"
      become: true

- name: Remove Disable-THP/Ulimit files
  block:
    - name: Remove disable-thp service to systemd (CentOS/RHEL 7+)
      ansible.builtin.file:
        path: /etc/systemd/system/disable-thp.service
        state: absent
      become: true
      notify:
        - Reload systemctl daemon
      when:
        - not use_tuned_thp
        - ansible_connection != "docker"
        - "'full' in group_names"

    - name: Remove ulimits
      ansible.builtin.file:
        path: /etc/security/limits.d/splunk_ulimits.conf
        state: absent
      become: true
      when: splunk_use_initd

# Not removing DMesg ini config due to defaults on some systems breaking

- name: Remove firewall artifacts
  when:
    - firewall_service != 'undefined'
    - configure_firewall | bool
    - "'full' in group_names"
  block:
    - name: Remove firewalld artifacts
      when: firewall_service == "firewalld"
      block:
        - name: Remove splunk firewalld service
          ansible.builtin.file:
            path: /etc/firewalld/services/{{ splunk_firewall_service }}.xml
            state: absent
          become: true

        - name: Remove firewalld service
          ansible.posix.firewalld:
            service: "{{ splunk_firewall_service }}"
            permanent: true
            state: enabled
            immediate: true
          notify: Reload firewalld
          become: true

    - name: Remove UFW ports
      community.general.ufw:
        port: "{{ item.number }}"
        proto: "{{ item.protocol }}"
        rule: allow
        state: reloaded
        comment: "{{ item.desc | default('') }}"
        delete: true
      become: true
      loop: "{{ splunk_firewall_ports }}"
      when: firewall_service == "ufw"

- name: Remove FACLs
  when: not least_privileged
  block:
    - name: Remove setfacl to logrotate script
      ansible.builtin.lineinfile:
        path: "{{ logrotate_file }}"
        line: '        /usr/bin/setfacl -Rm u:{{ splunk_nix_user }}:rx /var/log'
        state: absent
      become: true

    - name: Check if auditd.conf is present
      ansible.builtin.stat:
        path: /etc/audit/auditd.conf
      register: result_auditd_conf
      become: true

    - name: Remove line from /var/log/audit.log # noqa risky-file-permissions
      community.general.ini_file:
        path: /etc/audit/auditd.conf
        section: null
        option: log_group
        value: root
        state: present
      become: true
      notify:
        - Restart redhat auditd service
        - Restart non-redhat auditd service
      when: result_auditd_conf.stat.exists
